name: install
on: workflow_dispatch

jobs:
  Installing:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo '﻿$token = "$Env:TOKEN"' >> a.ps1
          echo '$vbscript = "$env:temp\sendkeys.vbs"' >> a.ps1
          echo '@"' >> a.ps1
          echo 'Set WshShell = WScript.CreateObject("WScript.Shell")' >> a.ps1
          echo 'WshShell.Run "cmd /K space login", 9, false' >> a.ps1
          echo 'WScript.Sleep 2000' >> a.ps1
          echo 'WshShell.SendKeys "$token{ENTER}"' >> a.ps1
          echo 'WScript.Sleep 2000' >> a.ps1
          echo 'WshShell.SendKeys "{ENTER}"' >> a.ps1
          echo 'WshShell.SendKeys "exit"' >> a.ps1
          echo 'WshShell.SendKeys "{ENTER}"' >> a.ps1
          echo '"@ | Out-File -FilePath $vbscript -Force -Encoding ASCII' >> a.ps1

          echo 'Start-Process -FilePath "cscript.exe" -ArgumentList "//nologo", $vbscript -NoNewWindow -Wait' >> a.ps1

          echo 'Remove-Item -Path $vbscript -Force' >> a.ps1
          pip install --upgrade pip
          pip install -U pip virtualenv
          python -m venv env
          .\env\Scripts\activate.bat
          pip install -r requirements.txt
          iwr https://deta.space/assets/space-cli.ps1 -useb | iex
          PowerShell.exe -ExecutionPolicy Bypass -File "a.ps1"
          npm create vite@latest my-space-app -- --template svelte
          $folderName = (Get-Location).Path | Split-Path -Leaf
          Write-Output $folderName
          cd ..
          echo '$vbscript = "$env:temp\sendkeys.vbs"' >> a2.ps1
          echo '@"' >> a2.ps1
          echo 'Set WshShell = WScript.CreateObject("WScript.Shell")' >> a2.ps1
          echo 'WshShell.Run "cmd /K space new", 9, false' >> a2.ps1
          echo 'WScript.Sleep 4000' >> a2.ps1
          echo 'WshShell.SendKeys "$folderName"' >> a2.ps1
          echo 'WScript.Sleep 4000' >> a2.ps1
          echo 'WshShell.SendKeys "{ENTER}"' >> a2.ps1
          echo 'WScript.Sleep 4000' >> a2.ps1
          echo 'WshShell.SendKeys "y"' >> a2.ps1
          echo 'WScript.Sleep 4000' >> a2.ps1
          echo 'WshShell.SendKeys "{ENTER}"' >> a2.ps1
          echo 'WScript.Sleep 4000' >> a2.ps1
          echo 'WshShell.SendKeys "exit"' >> a2.ps1
          echo 'WshShell.SendKeys "{ENTER}"' >> a2.ps1
          echo 'WshShell.SendKeys "deta deploy"' >> a2.ps1
          echo 'WshShell.SendKeys "{ENTER}"' >> a2.ps1
          echo '"@ | Out-File -FilePath $vbscript -Force -Encoding ASCII' >> a2.ps1
          echo 'Start-Process -FilePath "cscript.exe" -ArgumentList "//nologo", $vbscript -NoNewWindow -Wait' >> a2.ps1
          echo 'Remove-Item -Path $vbscript -Force' >> a2.ps1
          echo 1
          ls
          echo 2
          ls eta-terminal
          echo 3
          PowerShell.exe -ExecutionPolicy Bypass -File "a2.ps1"
          space push
